apiVersion: v1
kind: Namespace
metadata:
  name: dso202-assignment-01
  labels:
    kubernetes.io/metadata.name: dso202-assignment-01
    app.kubernetes.io/part-of: dso202-assignment-01
    environment: development