apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dso202-assignment-01
  labels:
    app: task-tracker
type: Opaque
stringData:
  DB_USER: "taskuser"
  DB_PASSWORD: "taskpass123"
  POSTGRES_USER: "taskuser"
  POSTGRES_PASSWORD: "taskpass123"